### ISSUE TITLE
Can't write some picture

### ISSUE THREAD

**Issue by namejm** [afriess/dexif#4]
With the Version of 2017/9/11, I test the ReadWriteTest.exe which compiled by Delphi, I find it can't write some picture.
the first picture is the b.jpg, the rest are results.
When I switch to Modified lab, the application dead, after comment out the codes in dmetadata.pas on line 890 and 891, the application no dead any more. 
`else
      dec(SectionCnt);  // Discard this section`
How to solve this problem?
![b](https://user-images.githubusercontent.com/31474998/33132914-02db7afe-cfd6-11e7-8b00-fe6e05dc9dbb.jpg)
![test1 can t write](https://user-images.githubusercontent.com/31474998/33133082-a3b1340a-cfd6-11e7-96ca-fc1cc7ad900a.jpg)
![test2 can t write](https://user-images.githubusercontent.com/31474998/33133540-17a581f8-cfd8-11e7-898c-47f6407314a6.jpg)
![dead when changed to modified](https://user-images.githubusercontent.com/31474998/33133725-a08789d0-cfd8-11e7-91db-38465e8605d1.jpg)

**Comment by namejm** [comment]
@wp-xyz @afriess

**Comment by afriess** [comment]
Can you test it with Lazarus ? I have actual no Delphi compiler available.

When i download your attached b.jpg and look with EXIFSpy into it, i see no Problem.
![exifspy](https://user-images.githubusercontent.com/17022012/33220198-a9e6e538-d146-11e7-8e0f-8d5611c2e1d0.JPG)
I hope all your EXIF is in this file included.

I can not understand your problem. What did you want to do with this testprogramm ? Does it work with the original files and makes only with your file trouble ?

Andreas

**Comment by namejm** [comment]
I can't compile the ExifSpay.exe with Lazarus, can you give me the exe vesrion?
![20171125145413](https://user-images.githubusercontent.com/31474998/33228224-dcd58382-d1f0-11e7-974b-8978f4fad797.jpg)

If the testprogramm executes normally, the **value read-back** column should contains some strings like below, but it is blank when I test some pictures,  It's not just this one.
![20171125145135](https://user-images.githubusercontent.com/31474998/33228260-c2a377f2-d1f1-11e7-8ad6-8060e995de87.jpg)

**Comment by namejm** [comment]
I write some codes like this:

procedure TForm1.Button1Click(Sender: TObject);
var
  ImgDate: TImgData;
begin
  ImgDate := TImgData.Create();
  if ImgDate.ProcessFile('b.jpg') then
  begin
    ImgDate.Comment := 'test';
    ImgDate.WriteEXIFJpegTo('test.jpg');
    if ImgDate.ProcessFile('test.jpg') then
      ShowMessage(ImgDate.Comment);
  end;

end;

when I test by the first picture in the top, the warning like this:
![20171130174216](https://user-images.githubusercontent.com/31474998/33424189-ff6f9e24-d5f5-11e7-865d-74d5ad9fb361.jpg)

and the test.jpg can't be recognized by pictureview application
when I test by another picture, the test.jpg is normal
How to solve this problem?

**Comment by afriess** [comment]
A compiled Version for Windows of ExifSpy is added in the Tool directory. You have only to unzip it.

The TKHexeditor and the KControls are from http://www.tkweb.eu./en/delphicomp 

What is the test.jpg ? Have this file a valid structure before ?  Do you want to copy the exifstructure  from 
 b.jpeg to test.jpg?

Andreas

**Comment by namejm** [comment]
Thanks for your ExifSpy.exe
The b.jpg is the first picture in this post, I don't know whether it has valid structure. When I use the code to save a new picture, the new one can't be recongnized by pictureview application.

**Comment by afriess** [comment]
Crosswriting to another picture is not supported nor tested. I think it can only done if the second exists.




Regards


Andreas Frieß







On Thu, Nov 30, 2017 at 3:51 PM +0100, "namejm" <notifications@github.com> wrote:












Thanks for your ExifSpy.exe

The b.jpg is the first picture in this post, I don't know whether it has valid structure. When I use the code to save a new picture, the new one can't be recongnized by pictureview application.

**Comment by namejm** [comment]
when I change another picture, the code can create a normal test.jpg, so I think some *.pas seem to be modified.

**Comment by wp-xyz** [comment]
Your file is big-endian, and there is still an endian issue in the exif-reader:
In dexifreadwrite, procedure TExifReader.ReadIFD, line 217 ("offs := ReadDWord(AStream);"), must be
offs := FixEndian32(ReadDWord(AStream)).

Andreas, I am not sure at which state my current repository is and I don't want to spend too much time with it. Therefore, could you apply this?

**Comment by afriess** [comment]
@wp-xyz: I'm sorry but no dexifreadwrite nor ReadIFD is in this repo found.

Andreas

**Comment by wp-xyz** [comment]
As I feared... My local repository have moved quite a lot away from your master; it is at some kind of "undefined" state because at some time I gave up developing dexif and to write my own "fpexif" which circumvents many of the dexif shortcomings - I've begun preparing a folder for it on ccr.

I'll fix the current issue for your master, though - promised.

**Comment by afriess** [comment]
Actual i say, it is not a good idea to write tags across the endian border. 

I think it is better to make an end with developing from this Version of dExif and rewrite it from ground. When i return from my buissnesstrip i will look for the issue and expand a test for it.

Spend your time wp-xyz for the fpexif.

Andreas

**Comment by wp-xyz** [comment]
> Actual i say, it is not a good idea to write tags across the endian border.

What do you mean?

I just committed my fixed version to your repository. It fixes the issue of the OP and some other compilation issues. This will complete my contribution here, Further work will go into fpexif only. If you want you can withdraw write permissions to your repo for me.

One remark on the current status of the unit tests: The read test for FocalLengthIn35mmFilm is failing with the 2nd image. In order to speed up format verification I had reduced the size of the images. The program I used for this purpose, however, did not adjust the FocalPlaneXResolution and FocalPlaneYResolution. Therefore, the routine Calc35mm which calculates the FocalLengthIn35mmFilm tag in dExif gets incorrect input parameters. I did not want to manipulate the test images any further. A possibility to overcome this issue would be to restore an old version of img9438,jpg and use it in the read test. The smaller image is needed only in the write/read test.

**Comment by namejm** [comment]
The version of 20171202 can read/write most pictures now, but application will hung when read this picture because of dead cycle.
![b](https://user-images.githubusercontent.com/31474998/33522273-bfdf853c-d823-11e7-983e-c376cd3ace83.jpg)

When I commented out the codes in dmetadata.pas on line 890 and 891(`else dec(SectionCnt); // Discard this section`), the application no dead any more, but ImgDate.ProcessFile('b.jpg') will fail.

**Comment by wp-xyz** [comment]
How did you create this file? It has a defective JPEG structure: valid jpeg begins with the bytes FF D8 FF..., this one begins with FF D8 3F... 

Since many programs are able to read it (IrfanView refuses) it should be fixable in principle. But dExif has so many short-comings that I decided to write my own "fpexif". This is available on Lazarus Code and Component Repository (https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/fpexif/). It does not choke on this file.

**Comment by namejm** [comment]
I downloaded it from network, but I forget the URL now.
Thanks for your fpexif, I'll test it.
I find a  graphics library called EXIV2(http://www.exiv2.org), It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the ICC Profile embedded within digital images in various formats, but it's for C++, can you translate it for delphi/Lazarus?

**Comment by wp-xyz** [comment]
> can you translate it for delphi/Lazarus?

No

**Comment by afriess** [comment]
There are some more libraries for Delphi and Exif. If you want to translate a C++ to Delphi, you must do it by yourself. 
My focus is on Lazarus/Freepascal only and to use some features of dExif and this port was a try to translate it to Freepascal and to understand Exif, not more.
